### ISSUE TITLE
Fix support for #define DEBUG 1

### ISSUE THREAD

**Issue by celskeggs** [mit-pdos/ward#43]
Currently, even with a couple of fixes in 7eb2bb60e4170058f8496a9f35a10a438123e513, turning on DEBUG doesn't work. QEMU crashes after printing `could not find a valid fat32 filesystem on 'ahci0.0p1'`

I suspect this is not a FAT32-related problem, because printing that is the last thing the FAT32 system does when it can't detect a filesystem; there's likely something else that DEBUG breaks.

It would be helpful to have ward build under DEBUG=1, for the sake of helping us debug other problems.

**Comment by fintelia** [comment]
There are a bunch of more granular debug flags that DEBUG=1 toggles, so we may be able to quickly narrow down which is the issue (or just rely on the working ones for now). For individual cases, it might also be possible to enable debug on a per-file basis

**Comment by fintelia** [comment]
Fixed by https://github.com/mit-pdos/ward/commit/7eb2bb60e4170058f8496a9f35a10a438123e513
